#!/bin/bash
date >> /home/box/parser/log/log
source /home/box/parser/parsenv/bin/activate  2>> /home/box/parser/log/errlog-$(date +%y%m%d)
echo "env" >> /home/box/parser/log/log
python /home/box/parser/manage.py parser_balalaiki 2>> /home/box/parser/log/errlog-$(date +%y%m%d)
echo "bala" >> /home/box/parser/log/log
echo "-------------------------------------------------------------------------------------------------------------" >> /home/box/parser/log/log

