# Generated by Django 2.2 on 2019-04-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lutner_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brandname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lutner_parser.Brandname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lutner_parser.Category'),
        ),
    ]
