# Generated by Django 2.2 on 2019-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutner_parser', '0002_auto_20190418_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='price',
            field=models.FloatField(),
        ),
    ]
