# Generated by Django 2.2 on 2019-04-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutner_parser', '0005_auto_20190420_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagelink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
