# Generated by Django 2.2 on 2019-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutner_parser', '0006_pagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
