# Generated by Django 2.2 on 2019-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutner_parser', '0007_auto_20190421_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelink',
            name='link',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
