# Generated by Django 2.2 on 2019-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutner_parser', '0010_auto_20190426_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
